### ISSUE TITLE
Dokumentacja

### ISSUE THREAD

**Issue by andrzejwp** [Sheaim/209226#2]
Proszę używać docbloków opisujących poszczególne metody, powinny zawierać opis danej metody i jej interfejsu, aby ułatwić innym korzystanie z metody. 

Komentarz

`Bardzo brzydkie rozwiazanie, ale nie mam pomyslu jak to zrobic ladniej`

nie pomoże nikomu we właściwy sposób użyć pańskiego kodu.

**Comment by Sheaim** [comment]
Oba problemy wynikają z braku czasu (przytoczona notatka jest nieusuniętym reliktem z czasów implementacji - konstruktor do którego się odnosi już nie korzysta z metody resize_array, przez co rzeczona metoda jest nieużywana.). Podstawowym celem było wysłanie działającej wersji - separacja i stworzenie odpowiedniej dokumentacji były celami długofalowymi, ale przyszedł deadline...

Program na lab2 (implementacja struktur danych) będzie już odpowiednio sformatowany, ponieważ będzie zbudowany na tym samym szkielecie.

**Comment by Sheaim** [comment]
Wrzuciłem wersję poprawioną i oczyszczoną z nieużywanych elementów. Rodzieliłem maina i definicje klas i funkcji (są w pliku spine.h). Dodałem swego rodzaju Debug Mode (domyślnie nie wyświetla na konsoli żadnych informacji na temat wykonywanych operacji, przy wpisaniu komendy DebugMode=1 odpala program w tym samym trybie co w poprzedniej wersji.
