### ISSUE TITLE
Rozmiar repo

### ISSUE THREAD

**Issue by andrzejwp** [Sheaim/209226#5]
Zacommitował Pan jakiś ogromny plik do repozytorium. Proszę poczytać o tym jak go z niego usunąć (uwaga, samo git rm nie wystarczy).

http://naleid.com/blog/2012/01/17/finding-and-purging-big-files-from-git-history

**Comment by Sheaim** [comment]
Przy poprzednich czystkach przeoczyłem parę binaries i .txt które sobie zostały w arrayach. Teraz powinno być w porządku.
Mam usunąć te pliki również z loga, czy nie jest to konieczne?
