### ISSUE TITLE
Interakcje

### ISSUE THREAD

**Issue by andrzejwp** [Sheaim/209226#6]
Sugeruję zrezygnować z interakcji i pobierania parametrów pracy programu z klawiatury, jak to jest np w 5bcd99af73b351af1353d6338a0c8e336635b555. Dość mocno utrudni to Panu dalsze prace i pomiary.

**Comment by Sheaim** [comment]
Tą zmianę już zaaplikowano do kolejnych zadań. Interfejs konsolowy z możliwością zmian w trakcie runtime był czymś w rodzaju eksperymentu - dodam, że nieudanego. Ponieważ ta wersja była wersją dostarczoną jako rozwiązanie to to co jest zostanie. Kolejne programy nie będą miały tego interfejsu - jego implementacja dla kolejnych wersji, choć możliwa, była by zbyt czasochłonna.
