### ISSUE TITLE
lab8

### ISSUE THREAD

**Issue by andrzejwp** [Sheaim/209226#8]
Brak implementacji BST, jest tylko AVL.
Brak, w związku z powyższym, porównania BST z AVL.
Brak nawet właściwej analizy złożoności czasowej AVL dla operacji Insert i Search.

**Comment by Sheaim** [comment]
Brak implementacji drzewa BST i porównania z AVL wynika z nieporozumienia (nie zorientowałem się, że wymaga Pan porównania BST z AVL), zostanie to poprawione najszybciej jak to możliwe.

Co do analizy złożoności czasowej AVL dla operacji insert i search są one niemożliwe ze względu na zbyt małą dokładność pomiaru czasu - zaimplementowane metody najwyraźniej wykonują swoje zadania zbyt szybko - niezależnie od rozmiaru drzewa (próbowałem do tysiąca elementów - wypisywanie trwało dłużej niż dodawanie czy wyszukiwanie...)

Przeprowadzę testy jeszcze raz, ewentualne poprawki powinny pojawić się w sprawozdaniu do środy.

**Comment by Sheaim** [comment]
Dodałem BST. Po przetestowaniu log file (logfileb.txt w folderze BST) zwrócił te same wyniki co log testów AVL...

Przerobię programy testujące, ale nie wiem czy uda mi się uzyskać wyniki które mają sens.

**Comment by Sheaim** [comment]
Znalazłem błąd który powodował brak prawidłowych wyników, zmiany już zostały wprowadzone do kodu. Jeszcze dzisiaj przerobię sprawozdanie i będzie gotowa ostateczna wersja.
